### ISSUE TITLE
Error in 'Generate CodeQL Results CSV' step

### ISSUE THREAD

**Issue by michaelkimball** [department-of-veterans-affairs/codeql-tools#15]
We have a self-hosted runner for our build.
```sh
        if [[ ! -v codeql ]]; then
          $(realpath /opt/hostedtoolcache/CodeQL/*/x64/codeql/codeql | head -n 1) database interpret-results $path --format=csv --output="$temp/codeql-scan-results-$language.csv"
        else
          codeql database interpret-results $path --format=csv --output="$temp/codeql-scan-results-$language.csv"
        fi
```
This errors with
```
realpath: ‘/opt/hostedtoolcache/CodeQL/*/x64/codeql/codeql’: No such file or directory
/opt/github-actions/vetext-runner/actions-runner/_work/_temp/f40f58ee-d0cc-44cd-a12d-1f2bab490840.sh: line 2: database: command not found
```
We don't have codeql on our runner.

Our workaround for this issue is in our custom build step we add codeql to the github path
```sh
echo "$CODEQL_DIST" >> $GITHUB_PATH
```
and set an environment variable name `codeql` to `true` in the job
```yaml
      - name: Run Code Scanning
        env:
          codeql: true
        uses: department-of-veterans-affairs/codeql-tools/codeql-analysis@main
        with:
          build_step_name: build_java
          language: java
          token: ${{ github.token }}
```

One way to fix this is to:
1. use the `codeql` binary that is defined in the previous actions codeql by adding `$CODEQL_DIST` to the path
2. default to using that binary with an input that has the option of using the version that is self-hosted (maybe a path or something).
